### PR TITLE
Update black to latest

### PR DESCRIPTION
**Pull request by cidrblock**
- Upgrade and enable black to latest in `.pre-commit-config.yaml`

Other changes made by `precommit.ci` via black upgrade

### CODE REVIEW

**Comment by cidrblock** [comment]
recheck

**Comment by cidrblock** [comment]
recheck

**Comment by cidrblock** [comment]
recheck

**Comment by cidrblock** [comment]
recheck

**Comment by cidrblock** [comment]
recheck

**Review by GomathiselviS — APPROVED** [review]

**Pull request merged**
