### PR TITLE
CI cleanup

### PR DESCRIPTION
**Pull request by cidrblock**
##### SUMMARY

Linting and formatting changes for std sanity/unit/integration tests

##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- New Module Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by cidrblock** [comment]
recheck

**Comment by cidrblock** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
mock ; python_version < '3.5'

in test-requirements.txt will help

**Comment by cidrblock** [comment]
recheck

**Pull request merged**
