### PR TITLE
Recursive filter plugins remove_keys | replace_keys | keep_keys

### PR DESCRIPTION
**Pull request by KB-perByte**
##### SUMMARY

New plugins 

- remove_keys
- replace_keys
- keep_keys

##### ISSUE TYPE

- New Module Pull Request

##### COMPONENT NAME

- remove_keys
- replace_keys
- keep_keys

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by KB-perByte** [comment]
recheck

**Review by ashwini-mhatre — APPROVED** [review]

**Review by NilashishC — APPROVED** [review]

**Comment by ashwini-mhatre** [comment]
Recheck

**Comment by KB-perByte** [comment]
recheck

**Comment by KB-perByte** [comment]
recheck

**Pull request merged**
