### PR TITLE
replace_keys: Add complex integration tests.

### PR DESCRIPTION
**Pull request by vbotka**
##### SUMMARY
Add integration tests.

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
ansible.utils.replace_keys

##### ADDITIONAL INFORMATION
```paste below
No additional info atm.
```

### CODE REVIEW

**Comment by vbotka** [comment]
ping.

**Comment by vbotka** [comment]
The last test `9.replace_keys regex` reveals a bug, I think. The filter doesn't preserve the order of the items in the list. I plan to file a bug after this PR is merged. What do you think?

```
- {XY_key_o2: a, p1_key_o1: a, p3_key_o3: a}
- ```
-

**Comment by vbotka** [comment]
I'm missing any details about failed integration tests. I've successfully tested the code localy before submitting it, of course. In Ansible 2.12 and Python 3.8.5 the playbook

```yaml
shell> cat pb-replace_keys.yml 
---
- name: Integration targets replace keys
  hosts: localhost
  gather_facts: false

  # Test integration
  # shell: ANSIBLE_ROLES_PATH=/scratch/vbotka.ansible.utils/tests/integration/targets

  roles:
    - utils_replace_keys
```
successfully completed all tasks and skipped the debug tasks as expected
```
localhost: ok=15   changed=0    unreachable=0    failed=0    skipped=9    rescued=0    ignored=0
```
I'm afraid there is a mismatch in the integration testing. The details show 1 failed and 16 passed tests
```
=========================== short test summary info ============================
FAILED tests/integration/test_integration.py::test_integration[utils_replace_keys]
======================== 1 failed, 16 passed in 37.01s =========================
```
How can I help? Any pointer?

**Comment by vbotka** [comment]
I don't understand the error (Test collection / integration / py3.9 / stable-2.12 (pull_request)). See the value of *result* below.

This is the task:

```yaml
- name: 1.replace_keys
  block:
    - name: 1.replace_keys debug
      debug:
        var: result|to_yaml
      when: debug_test|d(false)|bool
    - name: 1.replace_keys assert
      assert:
        that: result == target
        fail_msg: |-
          [ERR] Assertion failed
          result:
            {{ result|to_yaml|indent(2) }}
          target:
            {{ target|to_yaml|indent(2) }}
  vars:
    result: "{{ l1|ansible.utils.replace_keys(target=_target) }}"
    _target:
      - { before: p1, after: x1 }
      - { before: p2, after: x2 }
    target:
      - { p3: a, x1: a, x2: a }
      - { p3: b, x1: b, x2: b }
      - { p3: c, x1: c, x2: c }
  tags: replace_keys
````

and this is the error (logs_271/integration\ \ py3.9\ \ stable-2.12/10_Run\ integration\ tests.txt):

```yaml
2022-10-14T16:09:53.7077994Z TASK [utils_replace_keys : 1.replace_keys assert] ******************************                                                                                  
2022-10-14T16:09:53.7078691Z ^[[1;30mtask path: /home/runner/collections/ansible_collections/ansible/utils/tests/integration/targets/utils_replace_keys/tasks/complex1.yaml:8^[[0m             
2022-10-14T16:09:53.7079393Z ^[[0;31mfatal: [localhost]: FAILED! => {^[[0m                                                                                                                     
2022-10-14T16:09:53.7079928Z ^[[0;31m    "assertion": "result == target",^[[0m                                                                                                                 
2022-10-14T16:09:53.7080289Z ^[[0;31m    "changed": false,^[[0m                                                                                                                                
2022-10-14T16:09:53.7080641Z ^[[0;31m    "evaluated_to": false,^[[0m                                                                                                                           
2022-10-14T16:09:53.7082884Z ^[[0;31m    "msg": "[ERR] Assertion failed\nresult:\n  changed: false\n  failed: false\n  msg:\n  - {duplex: auto, enabled: true, name: eth0, speed: auto}\n  - d\
escription: Configured by Ansible - Interface 1\n    duplex: auto\n    enabled: true\n    mtu: 1500\n    name: eth1\n    speed: auto\n    vifs:\n    - {description: Eth1 - VIF 100, enabled: \
true, mtu: 400, vlan_id: 100}\n    - {description: Eth1 - VIF 101, enabled: true, vlan_id: 101}\n  - {description: Configured by Ansible - Interface 2 (ADMIN DOWN), enabled: false,\n    mtu:\
 600, name: eth2}\n\ntarget:\n  - {p3: a, x1: a, x2: a}\n  - {p3: b, x1: b, x2: b}\n  - {p3: c, x1: c, x2: c}\n"^[[0m                                                                          
2022-10-14T16:09:53.7083952Z ^[[0;31m}^[[0m
````

There is no problem with Python 3.8
(logs_271/integration\ \ py3.8\ \ stable-2.12/10_Run\ integration\ tests.txt)

**Review by NilashishC — APPROVED** [review]

**Review by Ruchip16 — APPROVED** [review]

**Comment by Ruchip16** [comment]
thank you for your contribution @vbotka :)

**Pull request merged**
