### PR TITLE
WIP: testing sanity job

### PR DESCRIPTION
**Pull request by dmsimard**
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/765

### CODE REVIEW

**Comment by dmsimard** [comment]
recheck

**Comment by ganeshrn** [comment]
recheck

**Comment by felixfontein** [comment]
@dmsimard any news on this?

**Comment by dmsimard** [comment]
@ganeshrn @felixfontein it's not on my immediate radar but was rather an attempt for what seemed like a quick win -- it actually requires more work than that and I haven't had the chance to come back to it.

I initially proposed a job that was more or less a copy of what we already have for github actions and it looked like this: https://github.com/dmsimard/ansible-zuul-jobs/commit/46eb1d8b11f82654eb039ff39204ce266c2610f6

After discussing the approach with @pabelanger, we thought it may be better to re-use one of the existing ansible-test jobs.

When trying that, I found out that the ``ansible-test`` command has some hardcoded parameters: https://github.com/ansible/ansible-zuul-jobs/blob/cd8e49d74f0e9a95a13a6dfbd85d0f2cc831e585/roles/ansible-test/tasks/main.yaml#L52-L57

So it doesn't allow -- for example, to remove the ``--python`` argument and pass ``--docker`` instead.

We would need to make that role a bit more flexible to allow that and then we could re-use it.

**Comment by pabelanger** [comment]
> @ganeshrn @felixfontein it's not on my immediate radar but was rather an attempt for what seemed like a quick win -- it actually requires more work than that and I haven't had the chance to come back to it.
> 
> I initially proposed a job that was more or less a copy of what we already have for github actions and it looked like this: [dmsimard/ansible-zuul-jobs@46eb1d8](https://github.com/dmsimard/ansible-zuul-jobs/commit/46eb1d8b11f82654eb039ff39204ce266c2610f6)
> 
> After discussing the approach with @pabelanger, we thought it may be better to re-use one of the existing ansible-test jobs.
> 
> When trying that, I found out that the `ansible-test` command has some hardcoded parameters: [ansible/ansible-zuul-jobs@`cd8e49d`/roles/ansible-test/tasks/main.yaml#L52-L57](https://github.com/ansible/ansible-zuul-jobs/blob/cd8e49d74f0e9a95a13a6dfbd85d0f2cc831e585/roles/ansible-test/tasks/main.yaml#L52-L57)
> 
> So it doesn't allow -- for example, to remove the `--python` argument and pass `--docker` instead.
> 
> We would need to make that role a bit more flexible to allow that and then we could re-use it.

I'll have new jobs up by Friday. For now, we'll just use different nodeset for each python to get something going.

Then we'll work to see about adding container images. Given we don't want to depend on docker for CI, and use podman. I am expecting some potential challenges for that work.

**Comment by felixfontein** [comment]
Asking once again: have you tried using `ansible-test sanity --docker` with podman (it does come with a docker CLI emulation tool IIRC)?

**Comment by pabelanger** [comment]
This can be closed, for now we've added --docker flag to new 'ansible-test-sanity-docker' jobs. We'll roll them out to collects over the next few days:

  https://github.com/ansible/ansible-zuul-jobs/pull/776

**Comment by Andersson007** [comment]
@dmsimard hi, ^ if you agree, could you please close the PR?

**Comment by cidrblock** [comment]
@dmsimard closing on your behalf to to age.

**Pull request closed without merging**
