### PR TITLE
Add changelog for v2.0.2

### PR DESCRIPTION
**Pull request by NilashishC**
Depends-On: https://github.com/ansible-collections/ansible.utils/pull/61
Signed-off-by: NilashishC <nilashishchakraborty8@gmail.com>

### CODE REVIEW

**Comment by NilashishC** [comment]
recheck

**Comment by rohitthakur2590** [comment]
recheck

**Comment by NilashishC** [comment]
recheck

**Comment by NilashishC** [comment]
recheck

**Pull request merged**
